### ISSUE TITLE
Suggestion : lava fishing

### ISSUE THREAD

**Issue by Blugori** [Scouter456/Nether_Depths_Upgrade#1]
Hi, I tested the mod and I found it awesome, that's great to have more life in the nether :)
I wondered if you were open to suggestions, even if the mod was published recently.
If so, I would like to suggest a lava fishing mechanic.
I play with the Aquaculture 2 mod, and asked them 2 years ago if they could add such a thing, that's what they answered : 

![image](https://user-images.githubusercontent.com/66573974/189117052-c1a44310-dbcb-4f81-a310-3abc4aa99527.png)

I don't know much things about modding, but if we could fish the content from your mod in the nether, that would be awesome !
Thanks for reading, and thanks for the mod anyway !

**Comment by Scouter456** [comment]
Thats a great suggestion and worth looking into for the future, would add some extra depth!

**Comment by Blugori** [comment]
Thanks for the new fishing feature !! I guess I can close this now :3
