### ISSUE TITLE
Blaze powder recipe 

### ISSUE THREAD

**Issue by xXUnholyWolfXx** [Scouter456/Nether_Depths_Upgrade#11]
I am running netherdepthsupgrade-2.0.1-1.18.2 I just updated my server and found that the original recipe for blaze powder has been removed completely. my players are asking if it can be placed back in or not?

**Comment by Scouter456** [comment]
That seems to be a mistake on my part, if you are using farmersdelight in your server you can go back to the previous version.
https://www.curseforge.com/minecraft/mc-mods/nether-depths-upgrade/files/4271274

**Comment by xXUnholyWolfXx** [comment]
ok thank you ^_^

**Comment by Scouter456** [comment]
Should be fixed now
