### ISSUE TITLE
Names weird in Fabric 1.19.2

### ISSUE THREAD

**Issue by ChickMeow12** [Scouter456/Nether_Depths_Upgrade#12]
All of the items are displaying some variation of 'item.netherdepthsupgrade.[item name]' when you hold or mouse over them, instead of the actual name. For instance, when I mouse over the Lava Pufferfish, the tooltip displays 'item.netherdepthsupgrade.lava_pufferfish'. The creative mode tabs also have this problem.

I'm using a pretty big amount of mods, including Farmer's Delight, so I thought that might have been the problem at first, but I logged in with just Nether Depths Upgrade, no other mods, and still encountered the issue.

**Comment by Scouter456** [comment]
Yes, it seems I have forgotten to remove a comma in the lang file, I will have this fixed in the coming update
