### ISSUE TITLE
[Forge] Compatability issues with better fishing rods mod.

### ISSUE THREAD

**Issue by Ketrai** [Scouter456/Nether_Depths_Upgrade#16]
Better fishing rods [1.0.0]
Nether Depths Upgrade [2.0.2]
Big Fish [1.0.0] (Though this mod still works as intended, and doesn't cause any issues when paired with just better fishing rods)

MC version [1.19.2]
Forge version [43.2.6]

Appears to have major compatability issues with better fishing rods. Better fishing rods rods are supposed to gain XP upon catching a fish (not treasure). This feature is broken. In addition, it stops any modded items from Better fishing rods to be fished up.

**Comment by Scouter456** [comment]
Thanks for the report, would you be able to test the jar and see if that fixes your issue
[netherdepthsupgrade-2.0.3-1.19.2.zip](https://github.com/Scouter456/Nether_Depths_Upgrade/files/11066641/netherdepthsupgrade-2.0.3-1.19.2.zip)

**Comment by Ketrai** [comment]
> Thanks for the report, would you be able to test the jar and see if that fixes your issue [netherdepthsupgrade-2.0.3-1.19.2.zip](https://github.com/Scouter456/Nether_Depths_Upgrade/files/11066641/netherdepthsupgrade-2.0.3-1.19.2.zip)

Thanks for the fast response!

I tested it a good bit to make sure it works (leveling, modded loot), and it seems to work flawlessly now.

**Comment by Ketrai** [comment]
Will you update the version on curseforge as well?

**Comment by Scouter456** [comment]
Yes, I will, the coming Monday or Tuesday it should be updated

**Comment by Scouter456** [comment]
The newest version should be available now
