### ISSUE TITLE
Redistribution

### ISSUE THREAD

**Issue by aaronliu0130** [Scouter456/Nether_Depths_Upgrade#17]
Do modpack authors have the right to redistribute this mod as an override jar, i.e. in Modrinth modpacks? Alternatively, would you like to release on Modrinth?

**Comment by Scouter456** [comment]
What kind of stuff are you overriding?

**Comment by aaronliu0130** [comment]
Sorry for the late response! Curseforge does not allow downloading mods from curseforge for modrinth modpacks. So when your mod is not available for download elsewhere, the only option is to redistribute the mod's `.jar` file inside the modpack and move the files to the `mods` directory. Manually moving files like this in a modpack is called overriding.

**Comment by aaronliu0130** [comment]
Also someone pointed out to me that curseforge lists the license! I guess this issue wasn't needed since it's MIT lol.
