### ISSUE TITLE
Lava glass is ineffective when working with rubidium

### ISSUE THREAD

**Issue by ghost** [Scouter456/Nether_Depths_Upgrade#18]
Lava glass is ineffective when working with rubidium

**Comment by Scouter456** [comment]
There isnt really anything I can do about that, since rubidium changes the whole liquid renderer and the method I implemented it with, doesnt get called anymore

**Comment by ghost** [comment]
> 



> since rubidium changes the whole liquid renderer and the method I implemented it with, doesnt get called anymore

No problem :)
