### ISSUE TITLE
1.19.2 Forge 41.3.25 Server Crash

### ISSUE THREAD

**Issue by Thisguyneedshelp** [Scouter456/Nether_Depths_Upgrade#2]
Hi, i commented the same on the curseforge, but my server is crashing on start up and heres the crash report https://mclo.gs/pE33RRB

**Comment by Scouter456** [comment]
Should be solved in the latest update! If you have anymore issues please report them

**Comment by Thisguyneedshelp** [comment]
i see the update and am going to try it now, but im worried cause you reopened the issue, is it still not working, i guess ill find out

**Comment by Thisguyneedshelp** [comment]
it seems to work, thank you

**Comment by Scouter456** [comment]
Awesome! I reopened it since you might not have checked it and if it didnt work again you had to make a new issue, but it seems I can close it now
