### ISSUE TITLE
Crash on game load (1.18.2 Forge)

### ISSUE THREAD

**Issue by genderneutralnoun** [Scouter456/Nether_Depths_Upgrade#22]
Title. The logs seem to complain about concurrentModificationException, which I think is an error when two mods try to edit the same thing? So probably a conflict. Thought you'd want to know about it regardless.
Here's my log: https://mclo.gs/nPfv4JE
Let me know if I need to provide any other info. I keep forgetting to turn on emails for github notifications though, so I might take a while to respond.

**Comment by Scouter456** [comment]
If you remove ndu does it still happen?

**Comment by genderneutralnoun** [comment]
Removing NDU fixes the crash, yes.

**Comment by Scouter456** [comment]
Could you try if this fixes it
[netherdepthsupgrade-3.0.0-1.18.2.zip](https://github.com/Scouter456/Nether_Depths_Upgrade/files/12004082/netherdepthsupgrade-3.0.0-1.18.2.zip)

**Comment by genderneutralnoun** [comment]
I tried, and it did! Thanks!
