### ISSUE TITLE
Possible incompatibility with Mythic Mounts

### ISSUE THREAD

**Issue by nvb-uy** [Scouter456/Nether_Depths_Upgrade#24]
There's a ticking entity crash when players ride any MM mount. MM Dev told me to redirect the issue here as it might be a possible incompat, as NDU is mentioned.

https://mclo.gs/X1mBpQn

**Comment by Scouter456** [comment]
What mod is MM? Nvm I saw the title. I will take a look at it when I am available this Sunday.

**Comment by nvb-uy** [comment]
👍🧉

**Comment by Scouter456** [comment]
Did you also try if it also happens without NDU?
I have tried reproducing it, however I rode an entity from MM and nothing happened with NDU installed.
What entity did the person try to ride, was it tamed and did they have any items on them, if so what? Also was it in the nether or in lava?

**Comment by Scouter456** [comment]
Yeah, I have tried mounting a dragon from mythic mounts with NDU installed, with and without enchanted boots with hell strider and in and outside of lava, however none seemed to be giving any errors.

**Comment by Scouter456** [comment]
Okay so I have tried to cause the error to happen again, however it hasn't happened for me so I can not do a whole lot about it(if its caused by NDU) unless you got some more information to provide.

**Comment by nvb-uy** [comment]
not related to NDU
