### ISSUE TITLE
Ticking player crash

### ISSUE THREAD

**Issue by Ultimushadow** [Scouter456/Nether_Depths_Upgrade#26]
I got this crash while swimming around and once while flying, Neruina disconnected me rather than crashing the game out but you can still see the log. I noticed Nether Depths Upgrade in the "Caused by" section but I have no idea why the mod is crashing in relation to player movement, I have Hell Strider on my boots but that's the only thing I would think relates the two

Log: [latest.log](https://github.com/Scouter456/Nether_Depths_Upgrade/files/12617346/latest.log)

Modpack is heavy as hell though so I don't know what did it

**Comment by Scouter456** [comment]
Thanks for the report, I will take a look at it.

**Comment by McModknower** [comment]
Someone else had the same crash, maybe the crash report can help to find the issue: https://gnomebot.dev/paste/1162391175035097169

**Comment by Scouter456** [comment]
Yeah thanks, I do know wht it might be happening, but I havent had a lot of time to fix it atm.

**Comment by Scouter456** [comment]
Fixed in coming update
