### ISSUE TITLE
Random crash when in another Dimension from Deeper and Darker mod, in Fabric 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [Scouter456/Nether_Depths_Upgrade#3]
[crash-2022-09-28_15.12.17-client.txt](https://github.com/Scouter456/Nether_Depths_Upgrade/files/9662451/crash-2022-09-28_15.12.17-client.txt)

**Comment by Scouter456** [comment]
Hello, thanks for the report I have uploaded a new version that should fix it 
https://www.curseforge.com/minecraft/mc-mods/nether-depths-upgrade/files/4010353

**Comment by TalEdd** [comment]
That was quick. Thanks for the update! 😊
