### ISSUE TITLE
I made russian translation of this mod, but I do not know where to upload it

### ISSUE THREAD

**Issue by doemty** [Scouter456/Nether_Depths_Upgrade#30]
Just as the topic says:
[ru_ru.json](https://github.com/Scouter456/Nether_Depths_Upgrade/files/13882436/ru_ru.json)
(I also did for Ocean's delight:
[ru_ru.json](https://github.com/Scouter456/Nether_Depths_Upgrade/files/13882442/ru_ru.json)
)

**Comment by Scouter456** [comment]
Thanks, however this mod already has a russian translation, but ocean's delight does not yet so I will be adding that one ^^
