### ISSUE TITLE
If the nether biomes in overworld, it does not generate vegetation from the mod and does not spawn mobs.

### ISSUE THREAD

**Issue by MrRain139** [Scouter456/Nether_Depths_Upgrade#34]
I made the generation of nether biomes in overworld, but the vegetation from this mod is not generated and mobs do not spawn, although with other mods that add anything to the generation of nether problems were not. I would like it to be fixed.

**Comment by Scouter456** [comment]
I mean I dont know what you did so I cant help you if you want. Furthermore I have tried adding it to the overworld before and it worked fine so I wonder if there is something you are doing wrong, but as I said before I dont know what you did so I cant help you with it

**Comment by MrRain139** [comment]
I made a simple datapack mod for myself that would generate nether in the overworld below - 64. https://drive.google.com/file/d/1XrTAy8m6gvAyklvnCK1dUAIk9BDVZMbn/view?usp=sharing 
It needs mod patched to work 
https://www.curseforge.com/minecraft/mc-mods/patched/files/all?page=1&pageSize=20

**Comment by Scouter456** [comment]
Right I see that it is a fabric project, on fabric I am only checking if its the nether dimension so it wont work for that right now. I wont be able to fix this soon, but perhaps I can do it on next update.

**Comment by MrRain139** [comment]
> Right I see that it is a fabric project, on fabric I am only checking if its the nether dimension so it wont work for that right now. I wont be able to fix this soon, but perhaps I can do it on next update.

I also checked through the Sinytra Connector and forge version of your mod, but this error was present there too.

**Comment by Scouter456** [comment]
This should not be the case since there is no check for dimension in there and only biomes. But if you want compatibility you should probably add it yourself then, since you were able to make this mod adding compat for this mod shouldnt be that difficult
