### ISSUE TITLE
request: option to reel in items instead of entities

### ISSUE THREAD

**Issue by reefridgeerator** [Scouter456/Nether_Depths_Upgrade#35]
is it possible to have a config option to reel in the fish item like in vanilla minecraft instead of the mob itself? reeling in entities is admittedly really cool but it would be nice to have consistency between vanilla fishing and nether fishing. (also the fish keep falling back into the lava)

btw I love the mod, minecraft has a sore lack of fish and your models look amazing (the bone fish are my favourite). The compatibility with farmer's delight is also a really nice surprise :3

**Comment by Scouter456** [comment]
It is already possible to do this, it is an option in the config
