### ISSUE TITLE
[Forge 1.19.2] Kelp block vanishing

### ISSUE THREAD

**Issue by wiredwhiskers** [Scouter456/Nether_Depths_Upgrade#36]
Hi! I'm not sure if this is an intentional feature but it seems like the Warped Kelp Block and Crimson Kelp Block, when right clicked with any other block, will place the block and erase the kelp block entirely.

**Comment by Scouter456** [comment]
Thanks for your report however the 1.19.2 version wont be receiving anymore updates unless its a game breaking bug and this doesnt seem like it
