### ISSUE TITLE
[1.21] Neoforge Mod does not load Error SpawnPlacementRegisterEvent

### ISSUE THREAD

**Issue by Periam** [Scouter456/Nether_Depths_Upgrade#38]
Installing the latest version of the mod the game does not start.

Neoforge 21.0.79
netherdepthsupgrade-3.1.6.jar

![image](https://github.com/Scouter456/Nether_Depths_Upgrade/assets/13920185/ec6d390c-8bdf-4a01-b3ff-07fbdafaee60)

[crash-2024-07-10_09.56.08-fml.txt](https://github.com/user-attachments/files/16162338/crash-2024-07-10_09.56.08-fml.txt)

**Comment by Scouter456** [comment]
The 1.21 version was made using NF 21.0.0 it might be that in the recent updates something changed with this, so if you want to play with it you might have to downgrade NF for now until I release a more updated version
