### ISSUE TITLE
[Feature Request] Ability to Specify Mobs or Items in Fishing Loot Tables

### ISSUE THREAD

**Issue by Bentcheesee** [Scouter456/Nether_Depths_Upgrade#40]
In the fishing loot tables, items are what's contained, but it instead summons the mobs.  Would there be a way to instead create a loot table perimeter to instead specify if one is fishing up a mob instead of items?

The following image shows what the table currently looks like:
![image](https://github.com/user-attachments/assets/1e1acf6b-606f-49c4-aea8-09de3b7274a4)
This one is what the table could possibly look like for entities:
![image](https://github.com/user-attachments/assets/0969cc91-71f6-445f-9a31-a36bc8107eba)

The reason I'm asking is because it would be super cool to also be able to fish up different sea creatures, not even in the nether.  So one could specify fishing up a squid in the Overworld, or fish up one of the weird Better End fish while in the End.  Or even being able to fish up other things with custom ai/drops sort of like what Hypixel SkyBlock does with their fishing system.

**Comment by Scouter456** [comment]
There should already be a mod that you can do this with
<https://www.curseforge.com/minecraft/mc-mods/fishing-real>
