### ISSUE TITLE
a broken basalt columns configuredfeature that is trying to place blocks outside the 3x3 safe chunk area for features

### ISSUE THREAD

**Issue by NattoCB** [Scouter456/Nether_Depths_Upgrade#42]
version: 1.18.2

When I install NetherDepthsUpgrade with RepurposedStructures, it will keep spamming the warning log when the player walks around on the Basalt biome, not sure is it the only biome that has this error

`RepurposedStructures: Detected a mod with broken basalt columns configuredfeature that is trying to place blocks outside the 3x3 safe chunk area for features.  Find the broken mod and report to them to fix the placement of their basalt columns feature.`

if I remove NetherDepthsUpgrade then this log would be disappeared.
also, it will be larger than 400 MB if a player keeps walking lasting more than 10 minutes at the basalt biome, and will trigger a server lag for printing too much of these logs

According to the issue:
https://github.com/TelepathicGrunt/RepurposedStructures/issues/329
for 1.18.2 this log has not been removed, and the author advised to inform the target mod's author to address this issue properly.

Many thanks in advance

**Comment by Scouter456** [comment]
Does this happen with only repurposedstructures and ndu? Since it seems unlinkely since it doesnt add anything with the basaltcolumnfeature.

**Comment by NattoCB** [comment]
> Does this happen with only repurposedstructures and ndu? Since it seems unlinkely since it doesnt add anything with the basaltcolumnfeature.

Correct! as re-tested, this issue actually is an incompatibility issue between DistantHorizens and RepurposedStructure, thanks Scouter for the hint <3 this issue might able to be closed
