### ISSUE TITLE
[1.21] Hell Strider missing from vanilla enchantment tags

### ISSUE THREAD

**Issue by TelepathicGrunt** [Scouter456/Nether_Depths_Upgrade#44]
The enchantment will not show up in enchanting tables or random loot rolls, etc. It isn't even classified as a treasure or non-treasure enchantment which makes it difficult for other mod's to know how to handle your enchantment for compat.
 https://github.com/misode/mcmeta/tree/data-json/data/minecraft/tags/enchantment
 
 Here's the vanilla enchantment tags to look over. Be sure to add your enchantment to all vanilla tags that it fits under

**Comment by Scouter456** [comment]
Alright thanks for the issue, didnt know that was also needed its fixed now
