### ISSUE TITLE
[Fabric] SemVer Compliance

### ISSUE THREAD

**Issue by Franco227** [Scouter456/Nether_Depths_Upgrade#46]
Currently, the mod version is set to `fabric-3.1.8-1.21` in gradle.properties, which isn't compliant with SemVer and causes a warning when opening the game. It should be changed to `3.1.8+mc1.21-fabric` or something similar.

(I used the latest version here, but this is the case for all Fabric versions)

**Comment by Scouter456** [comment]
I dont really mind tbh its just a warning about a version name
 Thanks for the report anyways

**Comment by Franco227** [comment]
I know it's just a warning, but if all mod authors decided to ignore it it's just going to spam logs for no reason (which it currently does, sadly). If you REALLY don't want to do it yourself, I could do it and open pull requests.

**Comment by Franco227** [comment]
#47 #48 #49

**Comment by Poopooracoocoo** [comment]
Please reconsider! Fixing this is trivial
