### ISSUE TITLE
Mark 1.21.1 As Compatible Pls :)

### ISSUE THREAD

**Issue by Fyoncle** [Scouter456/Nether_Depths_Upgrade#51]

**Comment by Scouter456** [comment]
It should already be marked as such on curseforge

**Comment by Fyoncle** [comment]
> It should already be marked as such on curseforge

Not On Modrinth 
![image](https://github.com/user-attachments/assets/fd60152e-9804-4782-b15c-8de7949a3e8b)

**Comment by Scouter456** [comment]
Ah modrinth, should be done now

**Comment by Fyoncle** [comment]
> Ah modrinth, should be done now

Thanks ❤️
