### ISSUE TITLE
Fabric 1.19.2 - Crash without Farmer's Delight

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [Scouter456/Nether_Depths_Upgrade#8]
Hello!
When Farmers Delight is not installed, I get the following crash.
[latest.log](https://github.com/Scouter456/Nether_Depths_Upgrade/files/10438791/latest.log)

**Comment by Scouter456** [comment]
Thanks for the report, this will be fixed in the next update.

**Comment by Scouter456** [comment]
The latest version fabric-2.0.3-1.19.2 should have the fix for this, let me know if this fixed it for you or not.

**Comment by ZsoltMolnarrr** [comment]
Ohh I accidentally closed the issue. Sorry!
Yeah the problem seems to be fixed. :)
