### ISSUE TITLE
[1.19.2] [Fabric] All names are missing in newest version

### ISSUE THREAD

**Issue by lxly9** [Scouter456/Nether_Depths_Upgrade#9]
Every item's name is missing after downloading and replacing the old with the new version of the mod on fabric.

**Comment by lxly9** [comment]
you have a , too much and it corrupts the lang file

**Comment by Scouter456** [comment]
Could you provide some logs, debug.log, latest.log and crash report

**Comment by lxly9** [comment]
you dont need any logs, your lang file has a comma too much which in turn amkes the game skip the file. it's not a valid json
![grafik](https://user-images.githubusercontent.com/102386118/213890440-45f27e68-55e5-489f-b288-b6c530261e6b.png)
you had a comma after "itemGroup.netherdepthsupgrade.netherdepthsupgrade_food": "Nether Depths Upgrade Food". Remove it and its fixed

**Comment by lxly9** [comment]
I removed it myself to get the names back
